name = "CSCTrainingGround"
uuid = "ba5d0405-a961-418c-a8b6-c3f54ed333a3"
authors = ["josePereiro <jose.pereiro.personal@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
